---
- name: error handling playbook
  hosts: all
  become: true
  tasks:
  - name: installing httpd package
    yum:
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
  - name: starting httpd service
    service:
      name: http--
      state: started
    when: ansible_os_family == "RedHat"
    ignore_errors: yes
  - name: installing apache2 package
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
  - name: starting apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"
  - name: copying index file
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
