---
- name: my test playbook
  hosts: all
  become: true
  vars:
    item: ['raj','hari']
  tasks:
  - name: creating multiple users
    user: 
      name: '{{ item }}' 
      state: present
      # with_items: 
      # - raj
      # - hari
