---
- name: setup tomcat
  hosts: all
  become: true
  tasks:
  - name: installing java on redhat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"
  - name: installing java on debian
    apt:
      name: default-jdk
      state: installed
    when: ansible_os_family == "Debian"
  - name: download tomcat package
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.99/bin/apache-tomcat-8.5.99.tar.gz
      dest: /opt
  - name: extracting tomcat package
    unarchive:
      src: /opt/apache-tomcat-8.5.99.tar.gz
      dest: /opt
      remote_src: true
  - name: giving executing permisiions
    file:
      path: /opt/apache-tomcat-8.5.99/bin/startup.sh
      mode: 0777
  - name: starting tomcat service
    shell: ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.99/bin

